test_that("reading inexistent folder", {
  file <- system.file("HB-COVID0001", "101", "acqus", package = "nmr.parser")
  expe <- readExperiment(file)
  expect_equal(nrow(expe$acqus), 0)
  expect_length(expe, 9)
})

test_that("reading experiment folder", {
  file <- system.file("HB-COVID0001", "10", package = "nmr.parser")
  expe<- readExperiment(file)
  expect_equal(expe$acqus$acqus.TITLE, "Parameter file, TopSpin 3.5 pl 4")
  expect_equal(expe$acqus$acqus.NS, "32")
  expect_equal(expe$procs$value.PHC0, "-7.223511")
  expect_equal(expe$title$title, "PROF_PLASMA_NOESY Plasma {C:\\IVDrData\\data\\COVID19_Serum-20200701\\nmr} SamTrack {2  A3 - 203}")
  expect_equal(expe$eretic$ereticFactor, "3808.27187511")
  expect_equal(expe$lipo$value.TPTG, 139.84)
  expect_equal(expe$quant$value.Ethanol, "0.000")
  expect_equal(expe$lipo$value.TPTG, 139.84)
})

# test_that("reading experiment folders", {
#   folder <- file.path("~", "Downloads", "BRUKER_600_80", "600")
#   lof <- paste0(folder, "/", dir(folder), "/10")
#   expe<- readExperiment(lof)
#   expect_length(expe, 9)
#   expect_length(expe$acqus$path, 127)
#   expect_equal(nrow(expe$acqus), 127)
#   expect_equal(expe$acqus$path[1], "~/Downloads/BRUKER_600_80/600/32565/10/acqus")
#   expect_equal(expe$qc$infos[[1]]$name[1], "NMR Experiment Quality Test")
#   expect_equal(expe$qc$infos[[1]]$value[1], "passed")
#   expect_equal(expe$qc$tests[[1]]$name[1], "LineWidth in Hz")
#   expect_equal(expe$qc$tests[[1]]$value[1], "1.4")
#   expect_equal(expe$qc$tests[[1]]$refMax[1], "1.5")
#   expect_equal(expe$qc$tests[[2]]$name[1], "LineWidth in Hz")
#   expect_equal(expe$qc$tests[[2]]$value[1], "1.1")
#   expect_equal(expe$qc$tests[[1]]$name[2], "Residual Water Signal in mmol/L")
#   expect_equal(expe$qc$tests[[1]]$value[2], "20.0")
# })

